{{- if .Values.nodeExporter.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "synapse.fullname" . }}-node-exporter
  labels:
    {{- include "synapse.labels" . | nindent 4 }}
    app.kubernetes.io/component: node-exporter
spec:
  type: {{ .Values.nodeExporter.service.type }}
  ports:
    - port: {{ .Values.nodeExporter.service.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "synapse.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: node-exporter
{{- end }}
