{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "synapse.fullname" . }}-prometheus
  labels:
    {{- include "synapse.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      {{- if .Values.nodeExporter.enabled }}
      - job_name: 'node'
        static_configs:
          - targets: ['{{ include "synapse.fullname" . }}-node-exporter:{{ .Values.nodeExporter.service.port }}']
      {{- end }}
{{- end }}
