{{- if .Values.synapse.env.SLACK_BOT_TOKEN }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "synapse.fullname" . }}-secrets
  labels:
    {{- include "synapse.labels" . | nindent 4 }}
type: Opaque
data:
  slack-bot-token: {{ .Values.synapse.env.SLACK_BOT_TOKEN | b64enc | quote }}
{{- end }}
